/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: "ap-south-1",
  aws_cognito_identity_pool_id:
    "ap-south-1:6d7034c1-e87f-48fd-9234-3cf90cfa8ec9",
  aws_cognito_region: "ap-south-1",
  aws_user_pools_id: "ap-south-1_Y7kw5Lhjm",
  aws_user_pools_web_client_id: "42oc2mc3klgl3jmbd19mb8tot1",
  oauth: {},
};

export default awsmobile;
