/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-south-1",
    "aws_cognito_identity_pool_id": "ap-south-1:6d7034c1-e87f-48fd-9234-3cf90cfa8ec9",
    "aws_cognito_region": "ap-south-1",
    "aws_user_pools_id": "ap-south-1_Y7kw5Lhjm",
    "aws_user_pools_web_client_id": "42oc2mc3klgl3jmbd19mb8tot1",
    "oauth": {},
    "aws_user_files_s3_bucket": "track13dbe62744c74f0a90b3d9acc9e481c0162413-dev",
    "aws_user_files_s3_bucket_region": "ap-south-1",
    "aws_appsync_graphqlEndpoint": "https://rfsv3llnwrgjtn64fkhoeopjpy.appsync-api.ap-south-1.amazonaws.com/graphql",
    "aws_appsync_region": "ap-south-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-ghu5vgk2brabxatagvaj6uqxme"
};


export default awsmobile;
